name: Swift (iOS 18)

on: [push]

jobs:
  build:
    name: Swift ${{ matrix.swift }} on iOS
    strategy:
      matrix:
        os: [macos-15]
        swift: ["6.1"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: ðŸ¦¦ Install Swift Bundler
        run: |
          git clone https://github.com/stackotter/swift-bundler.git /tmp/swift-bundler
          cd /tmp/swift-bundler && swift build -c release
          sudo cp /tmp/swift-bundler/.build/release/swift-bundler /usr/local/bin/
      - name: ðŸ“¦ Build & Bundle
        run: swift bundler bundle -c release -p iOSSimulator UsdView
