name: Run Tests (Ubuntu x86/64)

on: [push]

jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        swift: ["6.1"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: ${{ matrix.swift }}
      - uses: actions/checkout@v4
      - name: ğŸ”„ Update apt cache
        run: sudo apt-get update
      - name: ğŸ‘¨â€ğŸ’» Install CxxStdlib
        run: sudo apt-get install -y libstdc++-12-dev
      - name: ğŸ—œï¸ Install DEFLATE
        run: sudo apt-get install -y libdeflate-dev
      - name: ğŸ“™ Install BZ2
        run: sudo apt-get install -y libbz2-dev
      - name: ğŸ““ Install ZLib
        run: sudo apt-get install -y zlib1g-dev
      - name: ğŸ Install Python
        run: sudo apt-get install -y python3-dev
      - name: ğŸ–¼ Install FreeGLUT
        run: sudo apt-get install -y freeglut3-dev
      - name: ğŸš€ Install Boost
        run: sudo apt-get install -y libboost-all-dev
      - name: ğŸ–¥ï¸ Install X11
        run: sudo apt-get install -y libxcursor-dev libxt-dev libxi-dev libxinerama-dev libxrandr-dev
      - name: ğŸ’» Install GTK
        run: sudo apt-get install -y libgtk-4-dev clang
      - name: ğŸ“¦ Build
        run: swift build -c debug --target UsdView
